### ISSUE TITLE
[feature] 冒险者科技官网-观点-官网博客开发

### ISSUE THREAD

**Issue by T0hsakaRin** [36node/36node.github.io#8]
### 调研静态博客框架，选取静态博客框架进行官网博客页面的前端开发：

* 官网工程为： https://github.com/36node/adventurer.tech ，请联系俊总获取工程权限，点击官网工程顶部导航《观点》后调转到本静态博客工程。
* 静态博客的header和footer部分沿用原工程 。https://github.com/36node/adventurer.tech
* 开发过程中有疑问欢迎在企业微信官网项目群内讨论。
* 原issue：https://github.com/36node/adventurer.tech/issues/10

### 开发建议：
* 静态博客可选gatsby框架：
  * https://www.boliball.com/yp63Vswica5FHmJGE479XP5k
  * https://www.gatsbyjs.org/
### 蓝湖设计稿：
* https://lanhuapp.com/url/6LJdq-VkLmv
* 需要参照设计稿进行web端和手机端的页面开发并实现相关功能

### 设计稿：
* 文章页
![PC_观点](https://user-images.githubusercontent.com/36887590/64595421-80e4e700-d3e4-11e9-978b-fbeb9c37112c.png)
* 文章详情：
![PC_观点_文章详情](https://user-images.githubusercontent.com/36887590/64595434-86423180-d3e4-11e9-8189-18a0e9d4d351.png)

**Comment by zjz1993** [comment]
已完成
